bowie = User.create(:username => "DavidBowie", :email => "ziggyplayedguitar@aol.com", :password => "wasthenazz")
prince = User.create(:username => "Prince&TheRevolution", :email => "sexymf@hotmail.com", :password => "Wh3nD0v3sCry")
elvis = User.create(:username => "ElvisPresley", :email => "graceland@altavista.org", :password => "lovemetender")
lennon = User.create(:username => "JohnLennon", :email => "PlasticOno@yahoo.com", :password => "0hY0k0")

orange = Book.create(:title => "A Clockwork Orange", :author => "Anthony Burgess", :year_of_publication => 1962, :category => "Fiction", :genre => "Science Fiction", :user_id => 1, :progress => "Finished", :user_rating => 5)
lunch = Book.create(:title => "Maked Lunch", :author => "William S. Burroughs", :year_of_publication => 1955, :category => "Fiction", :genre => "Beat", :user_id => 1, :progress => "Finished", :user_rating => 5, :user_review => "A window into one of the greatest and most terrifying minds of the 20th century.")
purple = Book.create(:title => "The Color Purple", :author => "Alice Walker", :year_of_publication => 1982, :category => "Fiction", :genre => "Epistolary", :user_id => 2, :progress => "Finished")
candide = Book.create(:title => "Candide", :author => "Voltaire", :year_of_publication => 1759, :category => "Fiction", :genre => "Satire", :user_id => 2, :progress => "In Progress")
orchid = Book.create(:title => "The Orchid Thief", :author => "Susan Orlean", :year_of_publication => 1998, :category => "Non-Fiction", :genre => "Biography", :user_id => 1, :progress => "Unread")
kingsrow = Book.create(:title => "Kings Row", :author => "Henry Bellamann", :year_of_publication => 1940, :category => "Fiction", :genre => "Coming-Of-Age", :user_id => 3, :progress => "Unread")
mines = Book.create(:title => "King Solomon's Mines", :author => "H. Rider Haggard", :year_of_publication => 1885, :category => "Fiction", :genre => "Adventure", :user_id => 3, :progress => "In Progress")
lear = Book.create(:title => "King Lear", :author => "William Shakespeare", :year_of_publication => 1608, :category => "Drama", :genre => "Tragedy", :user_id => 3, :progress => "Finished")
howl = Book.create(:title => "Howl And Other Poems", :author => "Allen Ginsburg", :year_of_publication => 1955, :category => "Poetry", :genre => "Beat", :user_id => 4, :progress => "Finished", :user_rating => 5, :user_review => "A cracking good poem.")
finn = Book.create(:title => "Finnegan's Wake", :author => "James Joyce", :year_of_publication => 1939, :category => "Fiction", :genre => "???", :user_id => 4, :progress => "In Progress")
bnw = Book.create(:title => "Brave New World", :author => "Aldous Huxley", :year_of_publication => 1955, :category => "Fiction", :genre => "Science Fiction", :user_id => 4, :progress => "Finished", :user_rating => 4, :user_review => "The world as it is, sad to say.")
